spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/registerapp
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation=true: true

    generate-ddl: true
    hibernate:
      ddl-auto: create

logging:
  level:
    root: info